const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');
const source=fs.readFileSync(__dirname+'/Code.gs','utf8');
function runtime(editable=true){let writes=0,photos=0;const data={472693755:[['NAMA'],['Test Staff']],142619344:[['Timestamp','Nama','Tanggal','Lokasi','Jam','Foto']],62551951:[['Timestamp','Nama','Tanggal','Lokasi','Jam','Foto']]};const fmt=(d,tz,pattern)=>{const p=Object.fromEntries(new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Jakarta',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(d).map(x=>[x.type,x.value]));return pattern==='yyyy-MM-dd'?`${p.year}-${p.month}-${p.day}`:pattern==='dd/MM/yyyy'?`${p.day}/${p.month}/${p.year}`:`${p.hour}:${p.minute}:${p.second}`};const sheets=Object.fromEntries(Object.entries(data).map(([id,rows])=>[id,{getLastRow:()=>rows.length,getRange:(r,c,n=1,m=1)=>({canEdit:()=>editable,getValues:()=>rows.slice(r-1,r-1+n).map(x=>x.slice(c-1,c-1+m)),getDisplayValues:()=>rows.slice(r-1,r-1+n).map(x=>x.slice(c-1,c-1+m)),setValues:v=>{rows[r-1]=v[0];writes++;},setNumberFormat:()=>{throw new Error('You cannot set the number format of cells in a typed column.')} })}]));const context={Date,Error,console:{error:()=>{}},ContentService:{MimeType:{JSON:'json'},createTextOutput:x=>({setMimeType:()=>JSON.parse(x)})},Utilities:{formatDate:fmt,parseDate:d=>new Date(d+'T00:00:00+07:00'),base64Decode:x=>Array.from(Buffer.from(x,'base64')),getUuid:()=> 'id',newBlob:()=>({})},PropertiesService:{getScriptProperties:()=>({getProperty:k=>k})},LockService:{getScriptLock:()=>({tryLock:()=>true,releaseLock:()=>{}})},SpreadsheetApp:{openById:()=>({getSheetById:id=>sheets[id]}),flush:()=>{}},DriveApp:{getFolderById:()=>({createFile:()=>{photos++;return{getUrl:()=> 'https://drive.google.com/file/test'}}})}};vm.createContext(context);vm.runInContext(source,context);return{run:p=>context.doPost({postData:{contents:JSON.stringify(p)}}),context,data,stats:()=>({writes,photos})}}
const entry={name:'test staff',mode:'WFO',action:'in',photo:'data:image/jpeg;base64,/9j/AA=='};
test('masuk stores six matching columns and one private photo; repeat does not duplicate',()=>{const r=runtime();assert.equal(r.run(entry).ok,true);assert.equal(r.run(entry).duplicate,true);assert.deepEqual(r.stats(),{writes:1,photos:1});assert.equal(r.data[142619344][1][3],'Kantor ARTA');assert.equal(r.data[142619344][1].length,6)});
test('pulang requires and stores a second photo',()=>{const r=runtime();r.run(entry);assert.equal(r.run({...entry,action:'out',photo:''}).ok,false);assert.equal(r.run({...entry,action:'out'}).ok,true);assert.equal(r.data[62551951][1][5],'https://drive.google.com/file/test');assert.deepEqual(r.stats(),{writes:2,photos:2})});
test('reject missing photo, unknown staff, WFA without location and checkout before checkin',()=>{for(const p of [{...entry,photo:''},{...entry,name:'Unknown'},{...entry,mode:'WFA'},{...entry,action:'out',photo:''}]){const r=runtime();assert.equal(r.run(p).ok,false);assert.equal(r.stats().writes,0)}});
test('WFA stores location; name whitespace/case resolves canonical HR name',()=>{const r=runtime();const v=r.run({...entry,name:' TEST   STAFF ',mode:'WFA',location:'Rumah — Yogya'});assert.equal(v.ok,true);assert.equal(v.name,'Test Staff');assert.equal(r.data[142619344][1][3],'WFA — Rumah — Yogya')});
test('date boundary uses Jakarta day and protects spreadsheet formulas',()=>{const r=runtime();assert.equal(r.context.dateKey_(new Date('2026-10-07T17:01:00Z')),'2026-10-08');assert.equal(r.context.dateKey_('07/10/2026'),'2026-10-07');assert.equal(r.context.safeText_('=IMPORTXML(1)'),"'=IMPORTXML(1)")});
test('invalid JPEG signature is rejected before upload',()=>{const r=runtime();assert.equal(r.run({...entry,photo:'data:image/jpeg;base64,SGVsbG8='}).ok,false);assert.deepEqual(r.stats(),{writes:0,photos:0})});

test('staff endpoint returns names only from configured staff tab',()=>{const r=runtime(); const result=r.context.doGet({parameter:{action:'staff'}});assert.equal(result.ok,true);assert.equal(JSON.stringify(result.staff),JSON.stringify(['Test Staff']));assert.equal(Object.keys(result).length,2)});

test('protected HR sheet returns actionable failure before uploading photo',()=>{const r=runtime(false);const result=r.run(entry);assert.equal(result.ok,false);assert.match(result.message,/Sheet absensi dikunci/);assert.deepEqual(r.stats(),{writes:0,photos:0})});
