const {test}=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');
const source=fs.readFileSync(__dirname+'/../../public/absensi/app.js','utf8');
function harness(camera,duplicate=false){
 const elements={}; const listeners={};let stopped=0,calls=[],created=0; const watermark=[];
 function element(id){return elements[id] ||= {hidden:false,disabled:false,value:'',textContent:'',videoWidth:640,videoHeight:480,readyState:3,options:[],children:[],setAttribute(n,v){this[n]=v},setCustomValidity(v){this.validation=v},scrollIntoView(){},append(v){this.children.push(v)},addEventListener(n,f){(listeners[id+':'+n] ||= []).push(f)},removeAttribute(n){delete this[n]},replaceChildren(...v){this.options=v;this.children=[...v]},add(v){this.options.push(v)},play:async()=>{},getContext:()=>({drawImage:()=>{},save(){},restore(){},measureText:text=>({width:text.length*8}),fillRect(){},fillText(text,x,y){watermark.push({text,x,y})}}),toDataURL:()=> 'data:image/jpeg;base64,/9j/AA=='};}
 const form=element('attendance');form.elements={mode:{value:'WFO'},action:{value:'in'}};form.reportValidity=()=>true;form.reset=()=>{form.elements.mode.value='';form.elements.action.value='in'};
 const track={stop:()=>stopped++,addEventListener:()=>{}};const stream={getTracks:()=>[track],getVideoTracks:()=>[track]};
 const document={hidden:false,getElementById:element,createElement:tag=>element(tag==='canvas'?'canvas':'created-'+(++created)),addEventListener:(n,f)=>{listeners['document:'+n]=[f]}};
 const context={document,window:{ARTA_ATTENDANCE:{endpoint:'https://example.test/exec'},isSecureContext:true,addEventListener:(n,f)=>{listeners['window:'+n]=[f]}},navigator:{onLine:true,mediaDevices:{getUserMedia:camera || (async()=>stream)}},Intl,Date,Option:function(text,value){this.text=text;this.value=value},AbortController,setTimeout,clearTimeout,setInterval:()=>{},fetch:async(url,opts)=>{calls.push({url,opts});return{ok:true,json:async()=>opts?.method==='POST'?{ok:true,duplicate,name:'Staff',mode:'WFO',date:'08/10/2026',time:'08:00:00'}:{ok:true,staff:['Staff']}}}};
 vm.createContext(context);vm.runInContext(source,context);
 return{elements,form,stream,document,calls,watermark,stopped:()=>stopped,settle:()=>new Promise(r=>setImmediate(r)),fire:async(id,type,event={})=>{for(const f of listeners[id+':'+type]||[])await f(event)}};
}
test('camera required, capture stops stream; checkout sends captured JPEG',async()=>{const h=harness();await h.settle();assert.equal(h.elements.submit.disabled,true);h.elements.name.value='Staff';await h.fire('name','input');await h.fire('name','keydown',{key:'Enter',preventDefault(){}});h.form.elements.action.value='out';await h.fire('open-camera','click');assert.equal(h.elements.capture.hidden,false);assert.equal(h.elements.submit.disabled,true);await h.fire('capture','click');assert.equal(h.stopped(),1);assert.equal(h.elements.submit.disabled,false);await h.fire('attendance','submit',{preventDefault(){}});const payload=JSON.parse(h.calls.find(c=>c.opts?.method==='POST').opts.body);assert.equal(payload.action,'out');assert.ok(payload.photo.startsWith('data:image/jpeg'));assert.equal(h.elements.success.hidden,false);assert.equal(h.elements['success-title'].textContent,'Selamat istirahat 👋☺️')});
test('camera permission denied blocks submission with actionable error',async()=>{const h=harness(async()=>{const e=new Error();e.name='NotAllowedError';throw e});await h.settle();await h.fire('open-camera','click');assert.equal(h.elements.submit.disabled,true);assert.match(h.elements.error.textContent,/ditolak/)});
test('changing employee clears photo',async()=>{const h=harness();await h.settle();h.elements.name.value='Staff';await h.fire('name','input');await h.fire('name','keydown',{key:'Enter',preventDefault(){}});await h.fire('open-camera','click');await h.fire('capture','click');await h.fire('attendance','change',{target:{name:'name'}});assert.equal(h.elements.submit.disabled,true);assert.equal(h.elements.preview.hidden,true)});
test('hiding tab stops live camera',async()=>{const h=harness();await h.settle();await h.fire('open-camera','click');h.document.hidden=true;await h.fire('document','visibilitychange');assert.equal(h.stopped(),1);assert.equal(h.elements.camera.hidden,true)});
test('late camera permission result after cancel is stopped',async()=>{let resolve;const h=harness(()=>new Promise(r=>resolve=r));await h.settle();const opening=h.fire('open-camera','click');await h.fire('cancel-camera','click');resolve(h.stream);await opening;assert.equal(h.stopped(),1);assert.equal(h.elements.submit.disabled,true)});
test('no file or gallery input exists in form',()=>{const html=fs.readFileSync(__dirname+'/../../public/absensi/index.html','utf8');assert.doesNotMatch(html,/type=["']file["']/);assert.match(html,/role="combobox"/);assert.match(html,/<video/)});

test('typed text must be selected from matching staff options',async()=>{const h=harness();await h.settle();h.elements.name.value='Sta';await h.fire('name','input');assert.equal(h.elements['staff-options'].children[0].textContent,'Staff');await h.fire('name','keydown',{key:'Enter',preventDefault(){}});assert.equal(h.elements.name.value,'Staff');assert.equal(h.elements.name.validation,'');h.elements.name.value='Not registered';await h.fire('name','input');assert.equal(h.elements.submit.disabled,true);assert.match(h.elements['staff-options'].children[0].textContent,/tidak ditemukan/)});

test('checkin greeting and current WIB clock',async()=>{const h=harness();await h.settle();assert.match(h.elements['current-time'].textContent,/^\d{2}:\d{2}:\d{2} WIB$/);h.elements.name.value='Staff';await h.fire('name','input');await h.fire('name','keydown',{key:'Enter',preventDefault(){}});await h.fire('open-camera','click');await h.fire('capture','click');await h.fire('attendance','submit',{preventDefault(){}});assert.equal(h.elements['success-title'].textContent,'Selamat bekerja 💪😍')});

test('captured JPEG includes all watermark fields at bottom left and location changes invalidate it',async()=>{
 const h=harness();await h.settle();h.elements.name.value='Staff';await h.fire('name','input');await h.fire('name','keydown',{key:'Enter',preventDefault(){}});
 h.form.elements.mode.value='WFA';h.form.elements.action.value='out';h.elements.location.value='Bandung';
 await h.fire('open-camera','click');await h.fire('capture','click');
 const text=h.watermark.map(line=>line.text).join('\n');
 for(const value of ['Nama: Staff','Tanggal:','Jam:','WIB','Mode: WFA','Lokasi: Bandung','Absensi: Pulang']) assert.ok(text.includes(value),value);
 assert.ok(h.watermark.every(line=>line.x>0&&line.x<100&&line.y>240&&line.y<480));
 assert.equal(h.elements.submit.disabled,false);await h.fire('location','input');assert.equal(h.elements.submit.disabled,true);assert.equal(h.elements.preview.hidden,true);
});

test('repeat submissions retain the greeting and show duplicate notice separately',async()=>{for(const action of ['in','out']){const h=harness(undefined,true);await h.settle();h.elements.name.value='Staff';await h.fire('name','input');await h.fire('name','keydown',{key:'Enter',preventDefault(){}});h.form.elements.action.value=action;await h.fire('open-camera','click');await h.fire('capture','click');await h.fire('attendance','submit',{preventDefault(){}});assert.equal(h.elements['success-title'].textContent,action==='in'?'Selamat bekerja 💪😍':'Selamat istirahat 👋☺️');assert.match(h.elements.receipt.textContent,/Absensi sudah tercatat sebelumnya/);}});
