import { ArrowRight, BarChart3, Building2, CheckCircle2, ChevronRight, CircleDollarSign, Compass, Layers3, LineChart, Mail, MapPin, ShieldCheck, Sparkles, Target, Workflow, Zap } from 'lucide-react';

const nav = ['About', 'What We Do', 'Solutions', 'Ecosystem', 'Investment', 'Culture', 'Contact'];
const stats = [['01', 'Business Checkup'], ['05', 'Public Brand Ecosystem'], ['360°', 'Growth Operations'], ['ID', 'Indonesia Market']];
const steps = [
  ['Identify', 'Business Checkup', 'Membaca performa, operasional, keuangan, pasar, customer behavior, brand positioning, dan peluang pertumbuhan.', Compass],
  ['Partner', 'Strategic Collaboration', 'Membangun kerja sama strategis dengan brand, owner, investor, partner lokasi, komunitas, dan stakeholder.', Building2],
  ['Accelerate', 'Development & Booster', 'Mempercepat pertumbuhan melalui sistem, marketing, operasional, finansial, development, dan eksekusi terukur.', Zap],
];
const solutions = [
  ['ARTAinsight', 'Strategic Consulting', 'Keputusan yang lebih tajam, realistis, dan berbasis data.', BarChart3],
  ['ARTAknowledge', 'Digital Product Enablement', 'Knowledge, template, sistem kerja, dan digital tools agar bisnis lebih rapi.', Workflow],
  ['ARTAcore', 'Financial & Operational System', 'Financial, operational, reporting, dan backend management untuk scale up.', ShieldCheck],
  ['ARTAos™', 'Full Service 360 Management', 'Manajemen end-to-end untuk operasional, finance, marketing, creative, dan development.', Layers3],
  ['ARTAccelerate', 'Marketing & Development Booster', 'Campaign, aktivasi, pengembangan pasar, dan akuisisi pelanggan.', LineChart],
];
const brands = [
  ['Sebelas Coffee', 'F&B', 'Coffee shop accessible untuk anak muda, mahasiswa, pelajar, pekerja muda, dan komunitas.'],
  ['Snapobox', 'Photobox', 'Pengalaman foto instan di coffee shop, lifestyle space, area kampus, dan pusat keramaian.'],
  ['Tunas Mekar Dental', 'Dental & Health', 'B2B dental, distribusi produk, support pembukaan klinik, dan health-related business.'],
  ['Balcos Compound', 'Commercial Compound', 'Lifestyle compound untuk komunitas, tenant, event, dan traffic-based activity.'],
  ['Zona Massage', 'Wellness', 'Wellness dan body care melalui massage, homecare, retention, dan customer experience.'],
];
const focus = ['Expansion CAPEX: outlet, booth, box, equipment, renovation, dan aset produktif.', 'Technology & Shared Service: sistem, tools, reporting, dashboard, dan workflow internal.', 'Working Capital & Reserve: cadangan operasional untuk stabilitas cash flow.'];
const impact = ['Inisiatif', 'Mutual', 'Praktis', 'Adaptif', 'Cerdas', 'Tuntas'];
const cermat = ['Cari akar masalah', 'Efektifkan proses', 'Rinci dan rapi', 'Mengukur dampak', 'Akurat', 'Teliti'];

function Badge({ children, dark = false }: { children: React.ReactNode; dark?: boolean }) { return <span className={`mono inline-flex items-center rounded-md border px-2 py-1 text-[11px] font-bold uppercase tracking-[.08em] ${dark ? 'border-white/16 bg-white/7 text-white/70' : 'border-[#141416]/10 bg-white text-[#141416]/60'}`}>{children}</span>; }
function Button({ children, href = '#contact', dark = false }: { children: React.ReactNode; href?: string; dark?: boolean }) { return <a href={href} className={`inline-flex items-center gap-2 rounded-lg border px-4 py-3 text-sm font-semibold transition ${dark ? 'border-white/15 bg-white text-[#141416] hover:bg-[#f3f1eb]' : 'border-[#141416] bg-[#141416] text-white hover:-translate-y-0.5 hover:bg-[#2a2a2e]'}`}>{children}<ArrowRight className="h-4 w-4" /></a>; }
function SectionHead({ eyebrow, title, text }: { eyebrow: string; title: string; text?: string }) { return <div className="mb-10 grid gap-5 lg:grid-cols-[.9fr_1.1fr]"><div><Badge>{eyebrow}</Badge><h2 className="mt-4 max-w-3xl text-4xl font-semibold tracking-[-.055em] text-[#141416] md:text-6xl">{title}</h2></div>{text && <p className="max-w-xl text-base leading-8 text-[#666a73] lg:pt-12">{text}</p>}</div>; }
function Card({ children, className = '' }: { children: React.ReactNode; className?: string }) { return <div className={`hairline rounded-2xl bg-white p-6 ${className}`}>{children}</div>; }

export default function Home() {
  return <main className="min-h-screen bg-[#fbfaf7] text-[#141416]">
    <div className="border-b border-white/10 bg-[#141416] px-4 py-2 text-center text-xs text-white/70"><span className="mr-2 rounded bg-[#ffb1ee]/10 px-1.5 py-0.5 font-mono text-[10px] font-bold uppercase tracking-wider text-[#ffb1ee] ring-1 ring-[#ffb1ee]/35">New</span> ARTA Partners website concept — minimal, professional, system-first.</div>
    <header className="sticky top-0 z-50 border-b border-[#141416]/10 bg-[#fbfaf7]/86 backdrop-blur-xl">
      <div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4"><a href="#home" className="flex items-center gap-2.5"><div className="grid h-9 w-9 place-items-center rounded-lg bg-[#141416] text-sm font-black text-white">A</div><div className="leading-none"><p className="font-semibold tracking-[-.03em]">ARTA</p><p className="mono text-[10px] uppercase tracking-[.18em] text-[#8a6b34]">partners</p></div></a><nav className="hidden items-center gap-6 text-sm font-medium text-[#141416]/60 lg:flex">{nav.map(n => <a href={`#${n.toLowerCase().replaceAll(' ', '-')}`} className="hover:text-[#141416]" key={n}>{n}</a>)}</nav><a href="#contact" className="rounded-lg border border-[#141416]/15 bg-white px-3 py-2 text-sm font-semibold shadow-sm">Contact</a></div>
    </header>

    <section id="home" className="grid-bg relative border-b border-[#141416]/10">
      <div className="mx-auto max-w-7xl px-5 py-20 md:py-28"><div className="max-w-5xl"><Badge>The Strategic Brand Partner</Badge><h1 className="mt-5 max-w-5xl text-5xl font-semibold leading-[.94] tracking-[-.075em] md:text-8xl">Strategic Brand Partner untuk pertumbuhan bisnis yang tangguh dan berkelanjutan.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-[#666a73]">ARTA Partners membantu brand potensial bertumbuh melalui business checkup, partnership, penguatan sistem, manajemen operasional, strategi finansial, marketing development, dan akselerasi bisnis yang terukur.</p><div className="mt-9 flex flex-wrap gap-3"><Button href="#about">Kenali ARTA</Button><a href="#ecosystem" className="inline-flex items-center gap-2 rounded-lg border border-[#141416]/12 bg-white px-4 py-3 text-sm font-semibold text-[#141416] shadow-sm">Lihat Brand Kami <ChevronRight className="h-4 w-4" /></a><a href="#investment" className="inline-flex items-center gap-2 rounded-lg border border-[#141416]/12 bg-[#f3f1eb] px-4 py-3 text-sm font-semibold text-[#141416]">Diskusi Partnership</a></div></div><div className="mt-16 grid border-y border-[#141416]/10 md:grid-cols-4">{stats.map(([n,l]) => <div key={l} className="border-[#141416]/10 py-6 md:border-r md:px-6"><p className="text-4xl font-semibold tracking-[-.06em]">{n}</p><p className="mono mt-2 text-xs uppercase tracking-[.08em] text-[#666a73]">{l}</p></div>)}</div></div>
    </section>

    <section id="about" className="mx-auto max-w-7xl px-5 py-20"><SectionHead eyebrow="Who We Are" title="ARTA bukan agency, bukan holding pasif." text="ARTA adalah partner strategis yang ikut membangun, membenahi, dan mengakselerasi brand potensial."/><div className="grid gap-5 lg:grid-cols-3"><Card className="lg:col-span-2"><p className="text-2xl leading-10 tracking-[-.03em]">Kami membantu brand membangun fondasi bisnis yang lebih kuat melalui strategi, sistem operasional, manajemen finansial, marketing, creative, development, dan eksekusi lintas fungsi.</p><p className="mt-6 leading-8 text-[#666a73]">Dengan pendekatan praktis, adaptif, dan berbasis data, ARTA membantu brand membaca peluang pasar, memperbaiki sistem internal, dan mengakselerasi pertumbuhan secara lebih terarah.</p></Card><Card className="bg-[#141416] text-white"><Badge dark>Our Vision</Badge><p className="mt-5 text-2xl font-semibold tracking-[-.04em]">Menjadi mitra strategis terpercaya bagi bisnis dan stakeholder.</p><p className="mt-5 leading-7 text-white/60">Melalui pendekatan strategis dan inovasi berkelanjutan.</p></Card></div></section>

    <section id="what-we-do" className="border-y border-[#141416]/10 bg-white py-20"><div className="mx-auto max-w-7xl px-5"><SectionHead eyebrow="What We Do" title="Identify. Partner. Accelerate." text="Tiga tahapan utama untuk membaca kondisi bisnis, membangun kolaborasi, lalu mengakselerasi pertumbuhan."/><div className="grid gap-4 md:grid-cols-3">{steps.map(([title,sub,text,Icon]: any, i) => <Card key={title} className="relative overflow-hidden"><span className="absolute right-5 top-4 text-7xl font-semibold tracking-[-.08em] text-[#141416]/5">0{i+1}</span><Icon className="h-6 w-6 text-[#a87a2d]"/><h3 className="mt-8 text-3xl font-semibold tracking-[-.05em]">{title}</h3><p className="mt-1 font-mono text-xs font-bold uppercase tracking-[.08em] text-[#8a6b34]">{sub}</p><p className="mt-5 leading-7 text-[#666a73]">{text}</p></Card>)}</div></div></section>

    <section id="solutions" className="mx-auto max-w-7xl px-5 py-20"><SectionHead eyebrow="Business Solutions" title="Solusi bisnis yang modular, rapi, dan siap disesuaikan." text="Dari strategic consulting hingga full-service 360 business management."/><div className="grid gap-px overflow-hidden rounded-2xl border border-[#141416]/10 bg-[#141416]/10 lg:grid-cols-5">{solutions.map(([name,type,text,Icon]: any) => <div key={name} className="bg-[#fbfaf7] p-6"><Icon className="h-6 w-6 text-[#a87a2d]"/><h3 className="mt-8 text-2xl font-semibold tracking-[-.045em]">{name}</h3><p className="mt-2 mono text-xs font-bold uppercase tracking-[.08em] text-[#666a73]">{type}</p><p className="mt-5 text-sm leading-7 text-[#666a73]">{text}</p></div>)}</div></section>

    <section id="ecosystem" className="border-y border-[#141416]/10 bg-[#141416] py-20 text-white"><div className="mx-auto max-w-7xl px-5"><div className="mb-10 grid gap-5 lg:grid-cols-[.9fr_1.1fr]"><div><Badge dark>Brand Ecosystem</Badge><h2 className="mt-4 max-w-3xl text-4xl font-semibold tracking-[-.055em] md:text-6xl">A multi-brand ecosystem with operating depth.</h2></div><p className="max-w-xl text-base leading-8 text-white/60 lg:pt-12">ARTA mengembangkan brand dari F&B, photobox, dental, commercial compound, hingga wellness.</p></div><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{brands.map(([name,cat,text]) => <div key={name} className="rounded-2xl border border-white/12 bg-white/[.045] p-6 transition hover:bg-white/[.07]"><div className="flex items-start justify-between gap-4"><div><h3 className="text-2xl font-semibold tracking-[-.04em]">{name}</h3><p className="mt-2 mono text-xs font-bold uppercase tracking-[.08em] text-[#d2ad68]">{cat}</p></div><ChevronRight className="h-5 w-5 text-white/35" /></div><p className="mt-6 leading-7 text-white/60">{text}</p></div>)}</div></div></section>

    <section id="investment" className="mx-auto max-w-7xl px-5 py-20"><SectionHead eyebrow="Investment with ARTA" title="Peluang investasi untuk ekspansi brand yang sudah berjalan." text="Untuk qualified investor yang ingin berpartisipasi dalam pertumbuhan ekosistem brand ARTA melalui struktur kerja sama resmi."/><div className="grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><Card><p className="text-xl leading-9 tracking-[-.025em]">Fokus pendanaan ARTA bukan membangun bisnis dari nol atau sekadar “bakar uang”, tetapi mendukung ekspansi brand yang telah berjalan, memiliki aset operasional, dan potensi pertumbuhan yang dapat direplikasi.</p><div className="mt-6 rounded-xl border border-[#141416]/10 bg-[#f3f1eb] p-4 text-sm leading-7 text-[#666a73]">Skema tersedia mulai dari Rp150.000.000 hingga Rp500.000.000 per slot. Detail yield, tenor, distribusi imbal hasil, dan mekanisme kerja sama diarahkan ke sesi diskusi resmi.</div><div className="mt-7 flex flex-wrap gap-3"><Button>Diskusi Investment</Button><a className="inline-flex items-center gap-2 rounded-lg border border-[#141416]/12 bg-white px-4 py-3 text-sm font-semibold">Request Investment Deck <ArrowRight className="h-4 w-4" /></a></div></Card><Card>{focus.map(x => <p key={x} className="mb-4 flex gap-3 leading-7 text-[#666a73]"><CircleDollarSign className="mt-1 h-5 w-5 shrink-0 text-[#a87a2d]" />{x}</p>)}<div className="mt-6 border-t border-[#141416]/10 pt-6"><Badge>Risk Mitigation</Badge><p className="mt-4 leading-7 text-[#666a73]">Perjanjian notaris, cadangan dana / escrow account, dan laporan berkala kepada investor.</p></div></Card></div></section>

    <section id="culture" className="border-y border-[#141416]/10 bg-white py-20"><div className="mx-auto max-w-7xl px-5"><SectionHead eyebrow="Culture & Values" title="IMPACT and CERMAT in every execution." text="Budaya kerja berorientasi dampak nyata, praktis, detail, dan terukur."/><div className="grid gap-5 lg:grid-cols-2"><Value title="IMPACT" items={impact}/><Value title="CERMAT" items={cermat}/></div></div></section>

    <section id="contact" className="mx-auto max-w-7xl px-5 py-20"><div className="rounded-[28px] bg-[#141416] p-6 text-white md:p-10"><div className="grid gap-10 lg:grid-cols-[.9fr_1.1fr]"><div><Badge dark>Contact</Badge><h2 className="mt-5 text-4xl font-semibold tracking-[-.055em] md:text-6xl">Let’s build sustainable growth together.</h2><p className="mt-6 max-w-lg leading-8 text-white/60">Untuk diskusi partnership, investment, kolaborasi brand, atau pengembangan bisnis bersama ARTA.</p><div className="mt-8 space-y-3 text-white/62"><p className="flex gap-3"><Mail className="h-5 w-5 text-[#d2ad68]" />hello@artapartners.id</p><p className="flex gap-3"><MapPin className="h-5 w-5 text-[#d2ad68]" />Jogja, Indonesia</p></div></div><form className="rounded-2xl border border-white/12 bg-white p-4 text-[#141416]"><div className="grid gap-3 md:grid-cols-2"><Input label="Nama"/><Input label="Perusahaan / Brand"/><Input label="Nomor WhatsApp"/><Input label="Email"/><label className="md:col-span-2"><span className="text-sm font-semibold">Jenis kebutuhan</span><select className="mt-2 w-full rounded-lg border border-[#141416]/10 bg-[#fbfaf7] px-3 py-3 outline-none"><option>Partnership</option><option>Investment</option><option>Brand Collaboration</option><option>Location Partnership</option><option>Career</option><option>Others</option></select></label><label className="md:col-span-2"><span className="text-sm font-semibold">Pesan</span><textarea className="mt-2 min-h-28 w-full rounded-lg border border-[#141416]/10 bg-[#fbfaf7] px-3 py-3 outline-none" /></label></div><button className="mt-4 inline-flex items-center gap-2 rounded-lg bg-[#141416] px-4 py-3 text-sm font-semibold text-white">Contact ARTA <ArrowRight className="h-4 w-4" /></button></form></div></div></section>

    <footer className="border-t border-[#141416]/10 px-5 py-8"><div className="mx-auto flex max-w-7xl flex-col gap-3 text-sm text-[#666a73] md:flex-row md:items-center md:justify-between"><p className="font-semibold text-[#141416]">ARTA Partners</p><p>Strategic Brand Partner untuk pertumbuhan bisnis yang tangguh dan berkelanjutan.</p></div></footer>
  </main>;
}
function Value({ title, items }: { title: string; items: string[] }) { return <Card><div className="flex items-center justify-between"><h3 className="text-3xl font-semibold tracking-[-.05em]">{title}</h3><Sparkles className="h-5 w-5 text-[#a87a2d]" /></div><div className="mt-6 grid grid-cols-2 gap-2">{items.map(i => <div key={i} className="rounded-lg border border-[#141416]/10 bg-[#fbfaf7] px-3 py-3 text-sm font-semibold">{i}</div>)}</div></Card>; }
function Input({ label }: { label: string }) { return <label><span className="text-sm font-semibold">{label}</span><input className="mt-2 w-full rounded-lg border border-[#141416]/10 bg-[#fbfaf7] px-3 py-3 outline-none ring-[#a87a2d]/20 focus:ring-4" /></label>; }
